/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
#ifndef _ETHERIP6_UAPI_H
#define _ETHERIP6_UAPI_H

enum {
	IFLA_ETHERIP6_UNSPEC,
	IFLA_ETHERIP6_LOCAL,
	IFLA_ETHERIP6_REMOTE,
	IFLA_ETHERIP6_LINK,
	IFLA_ETHERIP6_HOP_LIMIT,
	__IFLA_ETHERIP6_MAX,
};

#define IFLA_ETHERIP6_MAX (__IFLA_ETHERIP6_MAX - 1)

#endif
